###########################
#
# Github actions workflow
# https://github.com/features/actions
#
# Runs `npm test` to execute the tests defined within this repo.
#
###########################


    name: Test

    on: [push]

    jobs:
      build:
        name: Test Run
        runs-on: Ubuntu-20.04

        steps:
          - name: Checkout repo code
            uses: actions/checkout@v2
          - name: Install dependencies
            run: npm ci
          - name: Run tests
            run: npm test
            env:
              # The CI env var is a hint to our testing scripts
              # to report results in the correct format, etc
              CI: true